blueprints/actions.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user
from datetime import date

from forms import AquariumActionsForm
from models import Aquarium, Action
from db import db

actions_views = Blueprint("actions", __name__, url_prefix="/aquariums/<string:aquarium_id>/actions")


@actions_views.route("/")
@login_required
def index(aquarium_id):
    aquarium = Aquarium.query.filter_by(id=aquarium_id, user_id=current_user.id).first()
    if not aquarium:
        return redirect(url_for("aquariums.new"))

    return render_template("aquariums/actions_index.html", aquarium=aquarium, date=date)


@actions_views.route("/new/", methods=["GET", "POST"])
@login_required
def new(aquarium_id):
    form = AquariumActionsForm()
    aquarium = Aquarium.query.filter_by(id=aquarium_id, user_id=current_user.id).first()
    if not aquarium:
        return redirect(url_for("aquariums.new"))

    if form.validate_on_submit():
        action = Action(
            aquarium_id=aquarium.id,
            name=form.name.data,
            description=form.description.data,
            due_on=form.due_on.data
        )

        db.session.add(action)
        db.session.commit()
        return redirect(url_for("actions.index", aquarium_id=aquarium.id))
    return render_template("aquariums/actions_new.html", form=form, aquarium=aquarium)


@actions_views.route("/<string:action_id>/edit/", methods=["GET", "POST"])
@login_required
def edit(aquarium_id, action_id):
    action = Action.query.filter_by(id=action_id, aquarium_id=aquarium_id).first()
    if not action or action.aquarium.user_id != current_user.id:
        return redirect(url_for("actions.new", aquarium_id=aquarium_id))

    form = AquariumActionsForm(obj=action)
    if form.validate_on_submit():
        action.name = form.name.data
        action.description = form.description.data
        action.due_on = form.due_on.data

        db.session.add(action)
        db.session.commit()
        return redirect(url_for("actions.index", aquarium_id=action.aquarium.id))
    return render_template("aquariums/actions_edit.html", form=form, action=action)


@actions_views.route("/<string:action_id>/delete/", methods=["POST"])
@login_required
def delete(aquarium_id, action_id):
    action_query = Action.query.filter_by(id=action_id, aquarium_id=aquarium_id)
    action = action_query.first()
    if not action or action.aquarium.user_id != current_user.id:
        return redirect(url_for("actions.index", aquarium_id=aquarium_id))

    if action:
        aquarium = action.aquarium

        action_query.delete()
        db.session.commit()
        return redirect(url_for("actions.index", aquarium_id=aquarium.id))

    return redirect(url_for("aquariums.index"))

blueprints/aquariums.py
from flask import Blueprint, render_template, url_for, redirect
from flask_login import login_required, current_user

from forms import AquariumForm
from models import Aquarium
from db import db

aquariums_views = Blueprint("aquariums", __name__, url_prefix="/aquariums")


@aquariums_views.route("/")
@login_required
def index():
    aquariums = Aquarium.query.filter_by(user_id=current_user.id)
    return render_template("aquariums/aquariums_index.html", aquariums=aquariums)


@aquariums_views.route("/new/", methods=["GET", "POST"])
@login_required
def new():
    form = AquariumForm()
    if form.validate_on_submit():
        aquarium = Aquarium(
            user_id=current_user.id,
            name=form.name.data
        )
        db.session.add(aquarium)
        db.session.commit()
        return redirect(url_for("aquariums.index"))

    return render_template("aquariums/aquariums_new.html", form=form)


@aquariums_views.route("/<string:aquarium_id>/edit/", methods=["GET", "POST"])
@login_required
def edit(aquarium_id):
    aquarium = Aquarium.query.filter_by(id=aquarium_id, user_id=current_user.id).first()
    if not aquarium:
        return redirect(url_for("aquariums.new"))

    form = AquariumForm(obj=aquarium)
    if form.validate_on_submit():
        aquarium.name = form.name.data

        db.session.add(aquarium)
        db.session.commit()
        return redirect(url_for("aquariums.index"))

    return render_template("aquariums/aquariums_edit.html", form=form, aquarium=aquarium)


@aquariums_views.route("/<string:aquarium_id>/delete/", methods=["POST"])
@login_required
def delete(aquarium_id):
    aquarium = Aquarium.query.filter_by(id=aquarium_id, user_id=current_user.id).first()
    if aquarium:
        db.session.delete(aquarium)
        db.session.commit()
    return redirect(url_for("aquariums.index"))

blueprints/livestock.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user

from forms import AquariumLivestockForm
from models import Aquarium, Livestock
from db import db

livestock_views = Blueprint("livestock", __name__, url_prefix="/aquariums/<string:aquarium_id>/livestock/")


@livestock_views.route("/")
@login_required
def index(aquarium_id):
    aquarium = Aquarium.query.filter_by(id=aquarium_id, user_id=current_user.id).first()
    if not aquarium:
        return redirect(url_for("aquariums.new"))
    return render_template("aquariums/livestock_index.html", aquarium=aquarium)


@livestock_views.route("/new/", methods=["GET", "POST"])
@login_required
def new(aquarium_id):
    form = AquariumLivestockForm()
    aquarium = Aquarium.query.filter_by(id=aquarium_id, user_id=current_user.id).first()
    if not aquarium:
        return redirect(url_for("aquariums.new"))
    if form.validate_on_submit():
        livestock = Livestock(
            aquarium_id=aquarium.id,
            name=form.name.data,
            quantity=form.quantity.data,
            added_on=form.added_on.data
        )
        db.session.add(livestock)
        db.session.commit()
        return redirect(url_for("livestock.index", aquarium_id=aquarium.id))
    return render_template("aquariums/livestock_new.html", form=form, aquarium=aquarium)


@livestock_views.route("/<string:livestock_id>/delete/", methods=["POST"])
@login_required
def delete(aquarium_id, livestock_id):
    livestock_query = Livestock.query.filter_by(id=livestock_id, aquarium_id=aquarium_id)
    livestock = livestock_query.first()
    if not livestock or livestock.aquarium.user_id != current_user.id:
        return redirect(url_for("actions.index", aquarium_id=aquarium_id))

    if livestock:
        aquarium = livestock.aquarium
        livestock_query.delete(synchronize_session="fetch")
        db.session.commit()
        return redirect(url_for("livestock.index", aquarium_id=aquarium.id))

    # Entry doesn't exist
    return redirect(url_for("aquariums.index"))

templates/aquariums/actions_edit.html
{% extends "base.html" %}
{% block content %}
<div class="container bg-white p-3 mt-4">
    <h1>Edit Action</h1>
    <form action="{{ url_for('actions.edit', aquarium_id=action.aquarium.id, action_id=action.id) }}" method="POST">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.name.label }}
            {{ form.name(class="form-control" + (" is-invalid" if form.name.errors else "")) }}
            {% for error in form.name.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="form-group">
            {{ form.description.label }}
            {{ form.description(class="form-control" + (" is-invalid" if form.description.errors else "")) }}
            {% for error in form.description.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="form-group mb-2">
            {{ form.due_on.label }}
            {{ form.due_on(class="form-control" + (" is-invalid" if form.due_on.errors else "")) }}
            {% for error in form.due_on.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>
{% endblock %}

templates/aquariums/actions_index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="bg-white p-3 m-4">
        <h1>Actions for "{{ aquarium.name }}"</h1>
        <a href="{{ url_for('actions.new', aquarium_id=aquarium.id) }}">Add action</a>

        <div class="row mx-auto mt-3 g-3">
            {% for action in aquarium.actions %}
            <div class="col-md-6">
                <div class="card {{ 'border-danger' if date.today() > action.due_on else '' }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ action.name }}</h5>
                        <p class="card-text mb-1 overflow-auto" style="max-height: 150px">{{ action.description }}</p>
                        <a href="{{ url_for('actions.edit', aquarium_id=aquarium.id, action_id=action.id) }}"
                           class="btn btn-primary btn-sm">Edit</a>
                        <form action="{{ url_for('actions.delete', aquarium_id=action.aquarium.id, action_id=action.id) }}"
                              method="POST" class="d-inline">
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                        <p class="card-text"><small><b>Due On</b></small>
                            <small class="text-muted">{{ action.due_on }}</small></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/aquariums/actions_new.html
{% extends "base.html" %}
{% block content %}
<div class="container bg-white p-3 mt-4">
    <h1>New Action</h1>
    <form action="{{ url_for('actions.new', aquarium_id=aquarium.id) }}" method="POST">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.name.label }}
            {{ form.name(class="form-control" + (" is-invalid" if form.name.errors else "")) }}
            {% for error in form.name.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="form-group">
            {{ form.description.label }}
            {{ form.description(class="form-control" + (" is-invalid" if form.description.errors else "")) }}
            {% for error in form.description.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="form-group mb-2">
            {{ form.due_on.label }}
            {{ form.due_on(class="form-control" + (" is-invalid" if form.due_on.errors else "")) }}
            {% for error in form.due_on.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>
{% endblock %}

templates/aquariums/aquariums_edit.html
{% extends "base.html" %}
{% block content %}
<div class="container bg-white p-3 mt-4">
    <h1>Edit Aquarium</h1>
    <form action="{{ url_for('aquariums.edit', aquarium_id=aquarium.id) }}" method="POST">
        {{ form.csrf_token }}
        <div class="form-group mb-2">
            {{ form.name.label }}
            {{ form.name(class="form-control" + (" is-invalid" if form.name.errors else "")) }}
            {% for error in form.name.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>
{% endblock %}

templates/aquariums/aquariums_edit_form.html
{% extends "base.html" %}
{% block content %}
<div class="container bg-white p-3 mt-4">
    <h1>Edit Aquarium</h1>
    <form action="{{ url_for('aquariums.edit', aquarium_id=aquarium.id) }}" method="POST">
        {{ form.csrf_token }}
        <div class="form-group mb-2">
            {{ form.name.label }}
            {{ form.name(class="form-control" + (" is-invalid" if form.name.errors else "")) }}
            {% for error in form.name.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>
{% endblock %}

templates/aquariums/aquariums_index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="bg-white p-3 m-4">
        <h1>Aquariums</h1>
        <a href="{{ url_for('aquariums.new') }}">Create New</a>

        {% for aquarium in aquariums %}
        <div class="card mb-2">
            <div class="card-body">
                <h5 class="card-title">{{aquarium.name}}</h5>
                <p class="text-muted mb-0"># Actions: {{ aquarium.actions | length }}</p>
                <p class="text-muted my-1"># Livestock: {{ aquarium.livestock | length }}</p>

                <a href="{{ url_for('actions.index', aquarium_id=aquarium.id) }}" class="card-link">Actions</a>
                <a href="{{ url_for('livestock.index', aquarium_id=aquarium.id) }}" class="card-link">Livestock</a>
                <a href="{{ url_for('aquariums.edit', aquarium_id=aquarium.id) }}" class="card-link">Edit</a>
                <form class="d-inline" action="{{ url_for('aquariums.delete', aquarium_id=aquarium.id) }}"
                      method="post">
                    <button type="submit" class="card-link align-baseline btn btn-link text-danger">Delete</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/aquariums/aquariums_new.html
{% extends "base.html" %}
{% block content %}
<div class="container bg-white p-3 mt-4">
    <h1>New Aquarium</h1>
    <form action="{{ url_for('aquariums.new') }}" method="POST">
        {{ form.csrf_token }}
        <div class="form-group mb-2">
            {{ form.name.label }}
            {{ form.name(class="form-control" + (" is-invalid" if form.name.errors else "")) }}
            {% for error in form.name.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>
{% endblock %}

templates/aquariums/aquariums_new_form.html
{% extends "base.html" %}
{% block content %}
<div class="container bg-white p-3 mt-4">
    <h1>New Aquarium</h1>
    <form action="{{ url_for('aquariums.new') }}" method="POST">
        {{ form.csrf_token }}
        <div class="form-group mb-2">
            {{ form.name.label }}
            {{ form.name(class="form-control" + (" is-invalid" if form.name.errors else "")) }}
            {% for error in form.name.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>
{% endblock %}

templates/aquariums/livestock_index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="bg-white p-3 m-4">
        <h1>Livestock for "{{ aquarium.name }}"</h1>
        <a href="{{ url_for('livestock.new', aquarium_id=aquarium.id) }}">Add livestock</a>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Added On</th>
            </tr>
            </thead>
            <tbody>
            {% for livestock in aquarium.livestock %}

            <tr>
                <td class="align-middle">{{ livestock.name }}</td>
                <td class="align-middle">{{ livestock.quantity }}</td>
                <td class="align-middle">{{ livestock.added_on }}</td>
                <td class="align-middle">
                    <form action="{{ url_for('livestock.delete', aquarium_id=aquarium.id,livestock_id=livestock.id) }}" method="POST">
                        <button type="submit" class="btn btn-link text-danger">Delete</button>
                    </form>
                </td>

            </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/aquariums/livestock_new.html
{% extends "base.html" %}
{% block content %}
<div class="container bg-white p-3 mt-4">
    <h1>Add Livestock</h1>
    <form action="{{ url_for('livestock.new', aquarium_id=aquarium.id) }}" method="POST">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.name.label }}
            {{ form.name(class="form-control" + (" is-invalid" if form.name.errors else "")) }}
            {% for error in form.name.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="form-group">

            {{ form.quantity.label }}
            {{ form.quantity(class="form-control" + (" is-invalid" if form.quantity.errors else "")) }}
            {% for error in form.quantity.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="form-group mb-2">

            {{ form.added_on.label }}
            {{ form.added_on(class="form-control" + (" is-invalid" if form.added_on.errors else "")) }}
            {% for error in form.added_on.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>
{% endblock %}